-- ============================================
-- OSINT Data Tables DDL
-- Database: DEMO.DEMO
-- 
-- Run this script in Snowflake to create tables
-- for persisting external OSINT data sources.
--
-- ROW_TIMESTAMP = TRUE enables METADATA$ROW_LAST_COMMIT_TIME
-- for pipeline latency tracking and incremental processing.
-- See: https://docs.snowflake.com/en/user-guide/data-engineering/row-timestamps
-- ============================================

-- Enable row timestamps by default for this schema (optional)
-- ALTER SCHEMA DEMO.DEMO SET ROW_TIMESTAMP_DEFAULT = TRUE;

-- Earthquake data from USGS API
CREATE TABLE IF NOT EXISTS DEMO.DEMO.OSINT_EARTHQUAKES (
    ID VARCHAR(100) NOT NULL,
    MAGNITUDE FLOAT,
    PLACE VARCHAR(500),
    LATITUDE FLOAT,
    LONGITUDE FLOAT,
    DEPTH FLOAT,
    EVENT_TIME TIMESTAMP_NTZ,
    TSUNAMI BOOLEAN,
    ALERT_LEVEL VARCHAR(50),
    SIGNIFICANCE INT,
    SOURCE VARCHAR(50) DEFAULT 'USGS',
    INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (ID, INGESTED_AT)
)
ROW_TIMESTAMP = TRUE;

-- Weather alerts from NWS API
CREATE TABLE IF NOT EXISTS DEMO.DEMO.OSINT_WEATHER_ALERTS (
    ID VARCHAR(200) NOT NULL,
    EVENT VARCHAR(200),
    SEVERITY VARCHAR(50),
    HEADLINE VARCHAR(1000),
    DESCRIPTION VARCHAR(8000),
    AREAS VARCHAR(4000),
    ONSET TIMESTAMP_NTZ,
    EXPIRES TIMESTAMP_NTZ,
    SOURCE VARCHAR(50) DEFAULT 'NWS',
    INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (ID, INGESTED_AT)
)
ROW_TIMESTAMP = TRUE;

-- Cryptocurrency prices from CoinGecko API
CREATE TABLE IF NOT EXISTS DEMO.DEMO.OSINT_CRYPTO_PRICES (
    ID VARCHAR(100) NOT NULL,
    SYMBOL VARCHAR(20),
    NAME VARCHAR(200),
    PRICE_USD FLOAT,
    CHANGE_24H FLOAT,
    VOLUME_24H FLOAT,
    MARKET_CAP FLOAT,
    SOURCE VARCHAR(50) DEFAULT 'COINGECKO',
    INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (ID, INGESTED_AT)
)
ROW_TIMESTAMP = TRUE;

-- News articles from Reddit/GDELT
CREATE TABLE IF NOT EXISTS DEMO.DEMO.OSINT_NEWS (
    ID VARCHAR(100) NOT NULL,
    TITLE VARCHAR(2000),
    SOURCE_NAME VARCHAR(500),
    URL VARCHAR(2000),
    PUBLISHED_AT TIMESTAMP_NTZ,
    CATEGORY VARCHAR(100),
    DATA_SOURCE VARCHAR(50) DEFAULT 'REDDIT',
    INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (ID, INGESTED_AT)
)
ROW_TIMESTAMP = TRUE;

-- Aircraft positions from OpenSky Network
CREATE TABLE IF NOT EXISTS DEMO.DEMO.OSINT_AIRCRAFT (
    ICAO VARCHAR(20) NOT NULL,
    CALLSIGN VARCHAR(20),
    LATITUDE FLOAT,
    LONGITUDE FLOAT,
    ALTITUDE FLOAT,
    VELOCITY FLOAT,
    HEADING FLOAT,
    VERTICAL_RATE FLOAT,
    ON_GROUND BOOLEAN,
    SOURCE VARCHAR(50) DEFAULT 'OPENSKY',
    INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (ICAO, INGESTED_AT)
)
ROW_TIMESTAMP = TRUE;

-- Cyber threat indicators from abuse.ch/CISA
CREATE TABLE IF NOT EXISTS DEMO.DEMO.OSINT_CYBER_THREATS (
    ID VARCHAR(200) NOT NULL,
    THREAT_TYPE VARCHAR(100),
    INDICATOR VARCHAR(1000),
    CONFIDENCE INT,
    SEVERITY VARCHAR(50),
    SOURCE VARCHAR(100),
    FIRST_SEEN TIMESTAMP_NTZ,
    LAST_SEEN TIMESTAMP_NTZ,
    TAGS VARCHAR(1000),
    INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (ID, INGESTED_AT)
)
ROW_TIMESTAMP = TRUE;

-- Traffic camera feeds
CREATE TABLE IF NOT EXISTS DEMO.DEMO.OSINT_TRAFFIC_CAMERAS (
    ID VARCHAR(100) NOT NULL,
    NAME VARCHAR(500),
    LATITUDE FLOAT,
    LONGITUDE FLOAT,
    IMAGE_URL VARCHAR(2000),
    ROADWAY VARCHAR(500),
    BOROUGH VARCHAR(100),
    DIRECTION VARCHAR(50),
    SOURCE VARCHAR(50) DEFAULT '511NY',
    INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (ID, INGESTED_AT)
)
ROW_TIMESTAMP = TRUE;

-- Air quality readings from AirNow/OpenAQ
CREATE TABLE IF NOT EXISTS DEMO.DEMO.OSINT_AIR_QUALITY (
    STATION_ID VARCHAR(100),
    LOCATION VARCHAR(500),
    LATITUDE FLOAT,
    LONGITUDE FLOAT,
    AQI INT,
    CATEGORY VARCHAR(100),
    PARAMETER VARCHAR(50),
    OBSERVED_AT TIMESTAMP_NTZ,
    SOURCE VARCHAR(50) DEFAULT 'AIRNOW',
    INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (STATION_ID, PARAMETER, INGESTED_AT)
)
ROW_TIMESTAMP = TRUE;

-- Maritime vessel tracking from MarineTraffic/AIS
CREATE TABLE IF NOT EXISTS DEMO.DEMO.OSINT_VESSELS (
    MMSI VARCHAR(20) NOT NULL,
    IMO VARCHAR(20),
    NAME VARCHAR(200),
    SHIP_TYPE VARCHAR(100),
    LATITUDE FLOAT,
    LONGITUDE FLOAT,
    SPEED FLOAT,
    COURSE FLOAT,
    HEADING FLOAT,
    DESTINATION VARCHAR(500),
    ETA TIMESTAMP_NTZ,
    SOURCE VARCHAR(50) DEFAULT 'AIS',
    INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (MMSI, INGESTED_AT)
)
ROW_TIMESTAMP = TRUE;

-- Satellite positions from N2YO/CelesTrak
CREATE TABLE IF NOT EXISTS DEMO.DEMO.OSINT_SATELLITES (
    NORAD_ID INT NOT NULL,
    NAME VARCHAR(200),
    LATITUDE FLOAT,
    LONGITUDE FLOAT,
    ALTITUDE FLOAT,
    VELOCITY FLOAT,
    INCLINATION FLOAT,
    PERIOD FLOAT,
    OBJECT_TYPE VARCHAR(100),
    LAUNCH_DATE DATE,
    SOURCE VARCHAR(50) DEFAULT 'CELESTRAK',
    INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (NORAD_ID, INGESTED_AT)
)
ROW_TIMESTAMP = TRUE;

-- Data source registry (MCP endpoints, REST APIs)
CREATE TABLE IF NOT EXISTS DEMO.DEMO.OSINT_DATA_SOURCES (
    ID VARCHAR(100) NOT NULL,
    NAME VARCHAR(200) NOT NULL,
    CATEGORY VARCHAR(100),
    SOURCE_TYPE VARCHAR(50), -- REST, MCP, WEBSOCKET, RSS
    ENDPOINT_URL VARCHAR(2000),
    DESCRIPTION VARCHAR(2000),
    RATE_LIMIT VARCHAR(100),
    REQUIRES_API_KEY BOOLEAN DEFAULT FALSE,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    LAST_FETCH_AT TIMESTAMP_NTZ,
    LAST_FETCH_STATUS VARCHAR(50),
    RECORDS_FETCHED INT,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (ID)
)
ROW_TIMESTAMP = TRUE;

-- Enable row timestamps on existing tables (if they already exist)
ALTER TABLE DEMO.DEMO.OSINT_EARTHQUAKES SET ROW_TIMESTAMP = TRUE;
ALTER TABLE DEMO.DEMO.OSINT_WEATHER_ALERTS SET ROW_TIMESTAMP = TRUE;
ALTER TABLE DEMO.DEMO.OSINT_CRYPTO_PRICES SET ROW_TIMESTAMP = TRUE;
ALTER TABLE DEMO.DEMO.OSINT_NEWS SET ROW_TIMESTAMP = TRUE;
ALTER TABLE DEMO.DEMO.OSINT_AIRCRAFT SET ROW_TIMESTAMP = TRUE;
ALTER TABLE DEMO.DEMO.OSINT_CYBER_THREATS SET ROW_TIMESTAMP = TRUE;
ALTER TABLE DEMO.DEMO.OSINT_TRAFFIC_CAMERAS SET ROW_TIMESTAMP = TRUE;
ALTER TABLE DEMO.DEMO.OSINT_AIR_QUALITY SET ROW_TIMESTAMP = TRUE;
ALTER TABLE DEMO.DEMO.OSINT_VESSELS SET ROW_TIMESTAMP = TRUE;
ALTER TABLE DEMO.DEMO.OSINT_SATELLITES SET ROW_TIMESTAMP = TRUE;
ALTER TABLE DEMO.DEMO.OSINT_DATA_SOURCES SET ROW_TIMESTAMP = TRUE;

-- Insert data source registry entries
INSERT INTO DEMO.DEMO.OSINT_DATA_SOURCES (ID, NAME, CATEGORY, SOURCE_TYPE, ENDPOINT_URL, DESCRIPTION, RATE_LIMIT, REQUIRES_API_KEY)
SELECT * FROM VALUES
    ('usgs_earthquakes', 'USGS Earthquake API', 'Earthquakes', 'REST', 'https://earthquake.usgs.gov/fdsnws/event/1/', 'Real-time earthquake data from USGS', 'Unlimited', FALSE),
    ('nws_alerts', 'NWS Weather Alerts', 'Weather', 'REST', 'https://api.weather.gov/alerts/active', 'Active weather alerts from National Weather Service', 'Unlimited', FALSE),
    ('coingecko', 'CoinGecko API', 'Markets', 'REST', 'https://api.coingecko.com/api/v3/', 'Cryptocurrency prices and market data', '10-50 req/min', FALSE),
    ('opensky', 'OpenSky Network', 'Aviation', 'REST', 'https://opensky-network.org/api', 'Global ADS-B aircraft tracking', '400 req/day', FALSE),
    ('reddit_news', 'Reddit r/worldnews', 'News', 'REST', 'https://www.reddit.com/r/worldnews/hot.json', 'World news from Reddit', 'Rate limited', FALSE),
    ('adsb_lol', 'ADSB.lol', 'Aviation', 'REST', 'https://api.adsb.lol/v2', 'Unlimited free ADS-B data', 'Unlimited', FALSE),
    ('open_meteo', 'Open-Meteo', 'Weather', 'REST', 'https://open-meteo.com/', 'Free global weather API', 'Unlimited', FALSE),
    ('gdacs', 'GDACS', 'Disasters', 'REST', 'https://www.gdacs.org/gdacsapi/', 'Global disaster alerts', 'Unlimited', FALSE),
    ('airnow', 'AirNow', 'Air Quality', 'REST', 'https://www.airnow.gov/', 'EPA air quality data', 'Unlimited', FALSE),
    ('threatfox', 'ThreatFox', 'Cyber', 'REST', 'https://threatfox.abuse.ch/api/', 'IOC database', 'Unlimited', FALSE),
    ('cisa_alerts', 'CISA Alerts', 'Cyber', 'RSS', 'https://www.cisa.gov/uscert/ncas/alerts.xml', 'US cybersecurity alerts', 'Unlimited', FALSE),
    ('gdelt', 'GDELT Project', 'News', 'REST', 'https://api.gdeltproject.org/', 'Global news events database', 'Unlimited', FALSE),
    ('reliefweb', 'ReliefWeb', 'Disasters', 'REST', 'https://api.reliefweb.int/v1/', 'Humanitarian crisis data', 'Unlimited', FALSE),
    ('celestrak', 'CelesTrak', 'Space', 'REST', 'https://celestrak.com/', 'TLE orbital data', 'Unlimited', FALSE),
    ('meshtastic', 'Meshtastic', 'Sensors', 'MCP', 'https://meshtastic.io/', 'LoRa mesh network data', 'N/A', FALSE)
WHERE NOT EXISTS (SELECT 1 FROM DEMO.DEMO.OSINT_DATA_SOURCES WHERE ID = column1);

-- Create views for latest data with row timestamps exposed
-- METADATA$ROW_LAST_COMMIT_TIME shows when each row was committed to Snowflake
CREATE OR REPLACE VIEW DEMO.DEMO.OSINT_EARTHQUAKES_LATEST AS
SELECT 
    METADATA$ROW_LAST_COMMIT_TIME AS ROW_COMMIT_TIME,
    *
FROM DEMO.DEMO.OSINT_EARTHQUAKES
QUALIFY ROW_NUMBER() OVER (PARTITION BY ID ORDER BY INGESTED_AT DESC) = 1;

CREATE OR REPLACE VIEW DEMO.DEMO.OSINT_WEATHER_ALERTS_LATEST AS
SELECT 
    METADATA$ROW_LAST_COMMIT_TIME AS ROW_COMMIT_TIME,
    *
FROM DEMO.DEMO.OSINT_WEATHER_ALERTS
QUALIFY ROW_NUMBER() OVER (PARTITION BY ID ORDER BY INGESTED_AT DESC) = 1;

CREATE OR REPLACE VIEW DEMO.DEMO.OSINT_CRYPTO_PRICES_LATEST AS
SELECT 
    METADATA$ROW_LAST_COMMIT_TIME AS ROW_COMMIT_TIME,
    *
FROM DEMO.DEMO.OSINT_CRYPTO_PRICES
QUALIFY ROW_NUMBER() OVER (PARTITION BY ID ORDER BY INGESTED_AT DESC) = 1;

CREATE OR REPLACE VIEW DEMO.DEMO.OSINT_NEWS_LATEST AS
SELECT 
    METADATA$ROW_LAST_COMMIT_TIME AS ROW_COMMIT_TIME,
    *
FROM DEMO.DEMO.OSINT_NEWS
QUALIFY ROW_NUMBER() OVER (PARTITION BY ID ORDER BY INGESTED_AT DESC) = 1;

CREATE OR REPLACE VIEW DEMO.DEMO.OSINT_AIRCRAFT_LATEST AS
SELECT 
    METADATA$ROW_LAST_COMMIT_TIME AS ROW_COMMIT_TIME,
    *
FROM DEMO.DEMO.OSINT_AIRCRAFT
QUALIFY ROW_NUMBER() OVER (PARTITION BY ICAO ORDER BY INGESTED_AT DESC) = 1;

CREATE OR REPLACE VIEW DEMO.DEMO.OSINT_CYBER_THREATS_LATEST AS
SELECT 
    METADATA$ROW_LAST_COMMIT_TIME AS ROW_COMMIT_TIME,
    *
FROM DEMO.DEMO.OSINT_CYBER_THREATS
QUALIFY ROW_NUMBER() OVER (PARTITION BY ID ORDER BY INGESTED_AT DESC) = 1;

CREATE OR REPLACE VIEW DEMO.DEMO.OSINT_VESSELS_LATEST AS
SELECT 
    METADATA$ROW_LAST_COMMIT_TIME AS ROW_COMMIT_TIME,
    *
FROM DEMO.DEMO.OSINT_VESSELS
QUALIFY ROW_NUMBER() OVER (PARTITION BY MMSI ORDER BY INGESTED_AT DESC) = 1;

CREATE OR REPLACE VIEW DEMO.DEMO.OSINT_SATELLITES_LATEST AS
SELECT 
    METADATA$ROW_LAST_COMMIT_TIME AS ROW_COMMIT_TIME,
    *
FROM DEMO.DEMO.OSINT_SATELLITES
QUALIFY ROW_NUMBER() OVER (PARTITION BY NORAD_ID ORDER BY INGESTED_AT DESC) = 1;

-- View for measuring pipeline latency (time from event to Snowflake commit)
CREATE OR REPLACE VIEW DEMO.DEMO.OSINT_PIPELINE_LATENCY AS
SELECT 
    'EARTHQUAKES' AS DATA_SOURCE,
    COUNT(*) AS RECORD_COUNT,
    AVG(TIMESTAMPDIFF('second', EVENT_TIME, METADATA$ROW_LAST_COMMIT_TIME)) AS AVG_LATENCY_SECONDS,
    MAX(TIMESTAMPDIFF('second', EVENT_TIME, METADATA$ROW_LAST_COMMIT_TIME)) AS MAX_LATENCY_SECONDS,
    MIN(METADATA$ROW_LAST_COMMIT_TIME) AS OLDEST_COMMIT,
    MAX(METADATA$ROW_LAST_COMMIT_TIME) AS NEWEST_COMMIT
FROM DEMO.DEMO.OSINT_EARTHQUAKES
WHERE METADATA$ROW_LAST_COMMIT_TIME IS NOT NULL
  AND EVENT_TIME IS NOT NULL
GROUP BY 1

UNION ALL

SELECT 
    'WEATHER_ALERTS' AS DATA_SOURCE,
    COUNT(*) AS RECORD_COUNT,
    AVG(TIMESTAMPDIFF('second', ONSET, METADATA$ROW_LAST_COMMIT_TIME)) AS AVG_LATENCY_SECONDS,
    MAX(TIMESTAMPDIFF('second', ONSET, METADATA$ROW_LAST_COMMIT_TIME)) AS MAX_LATENCY_SECONDS,
    MIN(METADATA$ROW_LAST_COMMIT_TIME) AS OLDEST_COMMIT,
    MAX(METADATA$ROW_LAST_COMMIT_TIME) AS NEWEST_COMMIT
FROM DEMO.DEMO.OSINT_WEATHER_ALERTS
WHERE METADATA$ROW_LAST_COMMIT_TIME IS NOT NULL
  AND ONSET IS NOT NULL
GROUP BY 1

UNION ALL

SELECT 
    'NEWS' AS DATA_SOURCE,
    COUNT(*) AS RECORD_COUNT,
    AVG(TIMESTAMPDIFF('second', PUBLISHED_AT, METADATA$ROW_LAST_COMMIT_TIME)) AS AVG_LATENCY_SECONDS,
    MAX(TIMESTAMPDIFF('second', PUBLISHED_AT, METADATA$ROW_LAST_COMMIT_TIME)) AS MAX_LATENCY_SECONDS,
    MIN(METADATA$ROW_LAST_COMMIT_TIME) AS OLDEST_COMMIT,
    MAX(METADATA$ROW_LAST_COMMIT_TIME) AS NEWEST_COMMIT
FROM DEMO.DEMO.OSINT_NEWS
WHERE METADATA$ROW_LAST_COMMIT_TIME IS NOT NULL
  AND PUBLISHED_AT IS NOT NULL
GROUP BY 1

UNION ALL

SELECT 
    'CRYPTO_PRICES' AS DATA_SOURCE,
    COUNT(*) AS RECORD_COUNT,
    NULL AS AVG_LATENCY_SECONDS,
    NULL AS MAX_LATENCY_SECONDS,
    MIN(METADATA$ROW_LAST_COMMIT_TIME) AS OLDEST_COMMIT,
    MAX(METADATA$ROW_LAST_COMMIT_TIME) AS NEWEST_COMMIT
FROM DEMO.DEMO.OSINT_CRYPTO_PRICES
WHERE METADATA$ROW_LAST_COMMIT_TIME IS NOT NULL
GROUP BY 1

UNION ALL

SELECT 
    'AIRCRAFT' AS DATA_SOURCE,
    COUNT(*) AS RECORD_COUNT,
    NULL AS AVG_LATENCY_SECONDS,
    NULL AS MAX_LATENCY_SECONDS,
    MIN(METADATA$ROW_LAST_COMMIT_TIME) AS OLDEST_COMMIT,
    MAX(METADATA$ROW_LAST_COMMIT_TIME) AS NEWEST_COMMIT
FROM DEMO.DEMO.OSINT_AIRCRAFT
WHERE METADATA$ROW_LAST_COMMIT_TIME IS NOT NULL
GROUP BY 1;

-- Grant permissions (adjust as needed)
-- GRANT SELECT ON ALL TABLES IN SCHEMA DEMO.DEMO TO ROLE PUBLIC;
-- GRANT SELECT ON ALL VIEWS IN SCHEMA DEMO.DEMO TO ROLE PUBLIC;

COMMENT ON TABLE DEMO.DEMO.OSINT_EARTHQUAKES IS 'USGS earthquake data - auto-ingested from Situation Desk. ROW_TIMESTAMP enabled for latency tracking.';
COMMENT ON TABLE DEMO.DEMO.OSINT_WEATHER_ALERTS IS 'NWS weather alerts - auto-ingested from Situation Desk. ROW_TIMESTAMP enabled for latency tracking.';
COMMENT ON TABLE DEMO.DEMO.OSINT_CRYPTO_PRICES IS 'CoinGecko crypto prices - auto-ingested from Situation Desk. ROW_TIMESTAMP enabled for latency tracking.';
COMMENT ON TABLE DEMO.DEMO.OSINT_NEWS IS 'Reddit/GDELT news - auto-ingested from Situation Desk. ROW_TIMESTAMP enabled for latency tracking.';
COMMENT ON TABLE DEMO.DEMO.OSINT_AIRCRAFT IS 'OpenSky aircraft positions - auto-ingested from Situation Desk. ROW_TIMESTAMP enabled for latency tracking.';
COMMENT ON TABLE DEMO.DEMO.OSINT_DATA_SOURCES IS 'Registry of all OSINT data sources, REST APIs, and MCP endpoints. ROW_TIMESTAMP enabled.';
COMMENT ON VIEW DEMO.DEMO.OSINT_PIPELINE_LATENCY IS 'Pipeline latency metrics using METADATA$ROW_LAST_COMMIT_TIME for observability.';
